#%RAML 1.0 Trait
displayName: trackable
headers: 
  client-id:
    type: string | nil
    required: true
    description: client-id
  client-secret:
    type: string | nil
    required: true
    description: client-secret